name: CookieMonster
main: com.pi.coelho.CookieMonster.CookieMonster
version: 1.7.3.1
authors: [jascotty2, Coelho]
softdepend: [Vault]
commands:
  cookiemonster:
    description: Admin Commands
    usage: /<command> [reload|region define/list/remove]
    aliases: [cm]